import { TodoSnapshotIn } from './Todo'
import { TripStoreSnapshot } from './TripStore'

const preset: { [id: string]: TodoSnapshotIn } = {
    '1': {
        id: '1',
        type: 'accomodation',
        category: 'reservation',
        title: '숙박 예약',
        iconId: '🛌',
        note: '',
        isFlaggedToDelete: true,
    },
    '2': {
        id: '2',
        type: 'passport',
        category: 'FOREIGN',
        title: '여권',
        iconId: '여권',
        note: '미리미리 할 것',
        isFlaggedToDelete: true,
    },
    '3': {
        id: '3',
        type: 'currency',
        category: 'FOREIGN',
        title: '환전',
        iconId: '💱',
        note: '미리미리 할 것',
        isFlaggedToDelete: true,
    },
    '4': {
        id: '4',
        type: 'roaming',
        category: 'FOREIGN',
        title: '로밍',
        iconId: '📶',
        note: '미리미리 할 것',
        isFlaggedToDelete: true,
    },
    '5': {
        id: '5',
        type: 'visit-japan',
        category: 'FOREIGN',
        title: 'Visit Japan',
        iconId: '📝',
        note: '미리미리 할 것',
        isFlaggedToDelete: true,
    },
    '7': {
        id: '7',
        type: 'military-approvement',
        category: 'FOREIGN',
        title: '국외여행허가',
        iconId: '🛌',
        note: '',
        isFlaggedToDelete: true,
    },
    '8': {
        id: '8',
        type: 'SUPPLY',
        category: 'SUPPLY',
        title: '세면도구',
        iconId: '🧴',
        note: '',
        isFlaggedToDelete: true,
    },
    '9': {
        id: '9',
        type: 'SUPPLY',
        category: 'SUPPLY',
        title: '어댑터',
        iconId: '🔌',
        note: '',
        isFlaggedToDelete: true,
    },
    '10': {
        id: '10',
        type: 'SUPPLY',
        category: 'SUPPLY',
        title: '선글라스',
        iconId: '🕶',
        note: '',
        isFlaggedToDelete: true,
    },
    '11': {
        id: '11',
        type: 'SUPPLY',
        category: 'SUPPLY',
        title: '캐리어',
        iconId: '🧳',
        note: '',
        isFlaggedToDelete: true,
    },
    '12': {
        id: '12',
        type: 'SUPPLY',
        category: 'SUPPLY',
        title: '우산',
        iconId: '☂️',
        note: '',
        isFlaggedToDelete: true,
    },
}

export const defaultTrip = {
    todoMap: preset,
    todolist: {
        reservation: [],
        FOREIGN: [],
        SUPPLY: [],
    } as { [cateogry: string]: string[] },
    preset: Object.keys(preset).map(id => ({
        isFlaggedToAdd: true,
        item: id,
    })),
} as TripStoreSnapshot
